version: '3'

tasks:

  mongo-up:
    desc: run docker compose with mongo
    aliases: [up, m-up, mup]
    cmds:
      - docker compose --file deploy/docker-compose.yml --project-directory ./ up

  mongo-down:
    desc: stop (down) docker compose with mongo
    aliases: [down, m-down, mdown]
    cmds:
      - docker compose --file deploy/docker-compose.yml --project-directory ./ down

  run:
    desc: run app
    cmds:
      - go run ./cmd/main.go --config config/local.yml

  test:
    desc: run all tests
    aliases: [t]
    #dir: tests
    cmds:
      - go test -v -count=1 ./...

  test100:
    dasc: run all tests 100 times
    aliases: [t100]
    dir: tests
    cmds:
      - go test -v -count=100 ./...

  race:
    desc: run all tests with race flag
    cmds:
      - go test -v -race -count=1 ./...

  cover:
    desc: tests with coverege
    #dir: tests
    cmds:
      #- defer: rm coverage.out
      - go test -short -count=1 -race -coverprofile=coverage.out ./...
      #- export BROWSER=firefox
      - go tool cover -html=coverage.out
